---
title: "36-460/660 Final Project EDA"
author: "Alex Cheng, Melody Wang, Liz Chu, Kevin Ren"
date: "April 23rd, 2024"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: show
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("nflfastR")
library(espnscrapeR)
library("ggplot2")
library(tidyverse)
library(dplyr)
```

```{r cars}
df <- nflfastR::load_pbp()
df = clean_pbp(df)
# CLEAN DATA
# remove all plays that weren't rushes or passes (this means punts, kickoffs, special teams plays, aborted plays, qb spikes, etc.)
df$success = ifelse(df$down >= 3 & df$ydstogo > df$yards_gained, 0, df$success)
cleandf = df %>% 
  filter(play_type == "run" | play_type == "pass") %>% 
  filter(penalty == 0) %>% 
  filter(success == 1)
# remove all plays where a penalty occured - we only want normal plays
# set third downs that didnt get a first down as unsuccessful
# 3 1/2 we can think of other successes but this is the easiest one so far
# remove all unsuccessful plays
```

```{r, rankvattempt}

rush_data = scrape_team_stats_nfl(season = 2023, stats = "rushing", role = "offense")
rush_data = rush_data %>%
  arrange(rush_yds, desc=TRUE) %>%
  mutate(rush_rank = floor(rank(-rush_yds)))

rush_data = rush_data %>% select(-c("rush_yds"))
# rush rankings = highest rush yards

pass_data = scrape_team_stats_nfl(season = 2023, stats = "passing", role = "offense")
pass_data = pass_data %>% 
  arrange(pass_yds, desc=TRUE) %>% 
  mutate(pass_rank = floor(rank(-pass_yds)))

pass_data = pass_data %>% select(-c("pass_yds"))
# pass rankings = highest pass yards

ggplot(data=rush_data, aes(x=rush_rank, y=rush_att, label = team)) + geom_point(color='blue') + labs(
  title="Rush Rank vs. Rush Attempts", 
  x="Rush Rank", 
  y="Rush Attempts Made"
) + geom_text(hjust = 0, vjust = 0)
ggplot(data=pass_data, aes(x=pass_rank, y=pass_att, label = team)) + geom_point(color='red') + labs(
  title="Pass Rank vs. Pass Attempts", 
  x="Pass Rank", 
  y="Pass Attempts Made"
) + geom_text(hjust = 0, vjust = 0)
```

```{r, marginal}
frequencies = df %>% filter(is.na(down) == FALSE) %>% group_by(down) %>% summarize(freq = sum(pass_attempt, na.rm = TRUE)/(sum(pass_attempt, na.rm = TRUE) + sum(rush_attempt, na.rm = TRUE)))
frequencies = data.frame(down = 1:4, "Pass Frequency" = frequencies$freq, "Run Frequency" = 1 - frequencies$freq) %>% pivot_longer(-down)

ggplot(data = frequencies, aes(x = factor(down), y = value, fill = name)) + labs(x = "Down", y = "Play Frequency", fill = "Type", title = "Play Frequency By Down") + geom_bar(position = "dodge", stat = "identity")
```

```{r}
yardsvtest = df %>% filter(is.na(ydstogo) == FALSE) %>% group_by(ydstogo) %>% summarize(freq = sum(pass_attempt, na.rm = TRUE)/(sum(pass_attempt, na.rm = TRUE) + sum(rush_attempt, na.rm = TRUE)))
yardsvtest = data.frame(ydstogo = yardsvtest$ydstogo, "Pass Frequency" = yardsvtest$freq, "Run Frequency" = 1 - yardsvtest$freq)

legend_colors <- c("Pass" = "red", "Run" = "blue")

ggplot(data = yardsvtest, aes(x = ydstogo)) + 
  geom_line(aes(y = Pass.Frequency, color = "Pass")) + 
  geom_line(aes(y = Run.Frequency, color = "Run")) + 
  labs(title="How does distance to 1st down impact play type?", x="Distance from 1st down (yards)", y="Frequency of Play") + 
  scale_color_manual(values = legend_colors) + 
  theme_bw()
```
